const homeBtn = document.getElementById('home-btn')
const exampleConversions = document.getElementById('example0conversions')
const userCreatedConversions = document.getElementById('create-ur-own-conversions')
const sources = document.getElementById('sources')
exampleConversion.addEventListener('click', () => {})